# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch: # can be triggered manually
  push: # automatically run on changes to following paths
    paths:
      - ".github/workflows/draw.yml"
      - "config/**/*.keymap"
      - "config/**/*.dtsi"
      - "config/**/*.h"
      - "config/**/*.conf"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write # allow workflow to commit to the repo
    with:
      amend_commit: true
      west_config_path: "config"
      keymap_patterns: "config/corne.keymap" # path to the keymaps to parse
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "draw" # path to save produced SVG and keymap YAML files
      parse_args: "" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "corne:'-k crkbd/rev4_1/mini -l LAYOUT_split_3x5_3' " # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"
